import "./globals.css";
import { Roboto, Geist, Geist_Mono, Inter } from "next/font/google"; // TODO: 안쓰는 폰트 정리하기

import ThemeRegistry from "./ThemeRegistry";

import type { Metadata } from "next";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: '--font-roboto',
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <body className={`${interSans.variable} ${geistSans.variable} ${geistMono.variable} ${roboto.variable} antialiased`} >
          {children}
        </body>
      </ThemeRegistry>
    </html>
  );
}
